
on:
  issue_comment:
    types: [created, deleted]
    inputs:
      image-width:
        type: string
        description: template (.github/PROJECT_TEMPLATES/)
        required: true
      image-height:
        type: string
        description: template (.github/PROJECT_TEMPLATES/)
        required: true
  workflow_dispatch:
    inputs:
      image-width:
        type: string
        description: template (.github/PROJECT_TEMPLATES/)
        required: false
        default: 800
      image-height:
        type: string
        description: template (.github/PROJECT_TEMPLATES/)
        required: false
        default: 600

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install @octokit/action
      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          templateName: ${{ github.event.inputs.template }}
