
on:
  issue_comment:
    types: [created, deleted]
    inputs:
      image-location:  
        description: 'Where to save the generated image'
        required: false
        default: 'images'
      image-width:
        type: string
        description: 'The width of the generated image'
        required: true
        default: 800
      image-height:
        type: string
        description: 'The height of the generated image'
        required: true
        default: 600
  workflow_dispatch:
    inputs:
      image-location:  
        description: 'Where to save the generated image'
        required: false
        default: 'images'
      image-width:
        type: string
        description: 'The width of the generated image'
        required: false
        default: 800
      image-height:
        type: string
        description: 'The height of the generated image'
        required: false
        default: 600

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install @octokit/action
      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          image-location: ${{ github.event.inputs.image-location }}
          image-width: ${{ github.event.inputs.image-width }}
          image-height: ${{ github.event.inputs.image-height }}
